listOfGames = ['Deadlock moba', 'Dota 2', 'Valorant', 'League of Legends']
listOfGames.reverse()
print(listOfGames)
listOfGames.append('CounterStrike 2')
print(listOfGames)
listOfGames.sort(reverse=True)
print(listOfGames)
listOfGames.sort()
print(listOfGames)
print(sorted(listOfGames))
GameINolove = listOfGames.pop(0)
print(GameINolove)
GameIlove = listOfGames.pop(0)
print(GameIlove)
listOfGames.insert(0, 'Deadlock moba')
print(listOfGames)
dontlike = 'Valorant'
listOfGames.remove(dontlike)
print(listOfGames)